DECLARE
    c_dd DETAILDEMANDE_MERGE%ROWTYPE;
    CURSOR detaildemande IS SELECT * from DETAILDEMANDE_MERGE;
BEGIN
    OPEN detaildemande;
    LOOP
        FETCH detaildemande into c_dd;
        EXIT WHEN detaildemande%NOTFOUND;
        
        INSERT INTO DETAILDEMANDE (QUANTITEENLEVEE, REMARQUE, NODEMANDE, NOTYPEDECHET) VALUES ( 
            c_dd.QUANTITEENLEVEE, c_dd.REMARQUE, (SELECT DEMANDE_MERGE.NODEMANDE_MERGE FROM DEMANDE_MERGE WHERE DEMANDE_MERGE.NODEMANDE = c_dd.NODEMANDE), c_dd.NOTYPEDECHET
        );
        
         INSERT INTO DETAILCOLLECTE (QUANTITEENLEVEE, REMARQUE, NODEMANDE, NOTYPEDECHET) VALUES ( 
            c_dd.QUANTITEENLEVEE, c_dd.REMARQUE, (SELECT DEMANDE_MERGE.NODEMANDE_MERGE FROM DEMANDE_MERGE WHERE DEMANDE_MERGE.NODEMANDE = c_dd.NODEMANDE), c_dd.NOTYPEDECHET
        );
        
    END LOOP;
    CLOSE detaildemande;
END;