DROP TRIGGER checkQuantityDepot;
CREATE TRIGGER checkQuantityDepot
BEFORE INSERT OR UPDATE ON DETAILDEPOT 
FOR EACH ROW

DECLARE 
QUANTITEE_TOTALE_DECHET NUMBER;
QUANTITEE_EXCEPTION EXCEPTION;
BEGIN
    
    SELECT TOTAL INTO QUANTITEE_TOTALE_DECHET
    FROM (
        SELECT SUM(QUANTITEENLEVEE) AS TOTAL FROM DETAILCOLLECTE
            JOIN DEMANDE ON DEMANDE.NODEMANDE = DETAILCOLLECTE.NODEMANDE
            WHERE DEMANDE.NOTOURNEE = :NEW.NOTOURNEE
            AND DETAILCOLLECTE.NOTYPEDECHET = :NEW.NOTYPEDECHET
    );

    IF :NEW.QUANTITEDEPOSEE > QUANTITEE_TOTALE_DECHET THEN
        RAISE QUANTITEE_EXCEPTION;
    END IF;
    
END;