CREATE OR REPLACE PROCEDURE SET_DEMANDE_TOURNEE IS
    NB_TOURNEE NUMBER;
    CURSOR DEMANDES IS SELECT NODEMANDE FROM DEMANDE WHERE NOTOURNEE IS NULL;
    CU_DEMANDE DEMANDE.NODEMANDE%type;
    START_DATE date;
    END_DATE date;
BEGIN
    OPEN DEMANDES;
    LOOP
    FETCH DEMANDES INTO CU_DEMANDE;
    EXIT WHEN DEMANDES%NOTFOUND;
    
        SELECT DATEENLEVEMENT INTO START_DATE FROM (SELECT DATEENLEVEMENT FROM DEMANDE WHERE NODEMANDE = CU_DEMANDE);
        END_DATE := START_DATE + 3;
        SELECT NOTOURNEE INTO NB_TOURNEE
        FROM (
            SELECT NOTOURNEE FROM TOURNEE WHERE DATETOURNEE BETWEEN START_DATE AND END_DATE AND rownum = 1 order by datetournee asc
        );
    
        IF (NB_TOURNEE > 1) THEN
            UPDATE DEMANDE SET NOTOURNEE = NB_TOURNEE
            WHERE NODEMANDE = CU_DEMANDE;
        ELSE
            UPDATE DEMANDE SET ATRAITER = 1
            WHERE NODEMANDE = CU_DEMANDE;
        END IF;
        
    END LOOP;
    CLOSE DEMANDES;

END SET_DEMANDE_TOURNEE;