DROP TRIGGER checkQuantityDepot;
CREATE TRIGGER checkQuantityDepot
BEFORE INSERT OR UPDATE ON DETAILDEPOT 
FOR EACH ROW

DECLARE 
QUANTITEE_TOTALE_TOURNEE NUMBER;
QUANTITEE_TOTALE_DEPOT NUMBER;
QUANTITEE_EXCEPTION EXCEPTION;
PRAGMA EXCEPTION_INIT(QUANTITEE_EXCEPTION, -20001);
BEGIN
    
    SELECT TOTAL INTO QUANTITEE_TOTALE_TOURNEE
    FROM (
        SELECT SUM(QUANTITEENLEVEE) AS TOTAL FROM DETAILCOLLECTE
            JOIN DEMANDE ON DEMANDE.NODEMANDE = DETAILCOLLECTE.NODEMANDE
            WHERE DEMANDE.NOTOURNEE = :NEW.NOTOURNEE
            AND DETAILCOLLECTE.NOTYPEDECHET = :NEW.NOTYPEDECHET
    );

    SELECT TOTAL INTO QUANTITEE_TOTALE_DEPOT
    FROM (
        SELECT SUM(QUANTITEDEPOSEE) AS TOTAL FROM DETAILDEPOT 
            WHERE NOTOURNEE = :NEW.NOTOURNEE 
            AND NOTYPEDECHET = :NEW.NOTYPEDECHET
    );

    IF QUANTITEE_TOTALE_DEPOT + :NEW.QUANTITEDEPOSEE > QUANTITEE_TOTALE_TOURNEE THEN
        RAISE QUANTITEE_EXCEPTION;
    END IF;

    EXCEPTION
        WHEN QUANTITEE_EXCEPTION
            THEN RAISE_APPLICATION_ERROR(-20001, 'La quantité du dépôt pour ce type de déchêt est supérieur à la quantité récoltée pendant la tournée');
    
END;